### ISSUE TITLE
Using with firebase, front camera flips image when uploaded. 

### ISSUE THREAD

**Issue by hollowaytyl** [Awalz/SwiftyCam#18]
Everything looks good when I post an image taken with the back camera, but when I take one with the front and upload it, its flips the image and crops it out of view. Do you know why this happening?

**Comment by Awalz** [comment]
I think this has to do with how the framework saves the UIImage with the front facing camera. Rather than actually flippining the image, it just sets the orientation to leftmirrored. IOS reads this and displays it prooerly, but I suspect Firebase ignores this.

I'm going to look into this and fix in a future version. In the meantime, I would look into flipping the image manually before uploading if you detect an image was taken with the front facing camera.

Andrew

**Comment by Awalz** [comment]
Issue has been resolved in Version 2.2.0
