### ISSUE TITLE
iPhone X & newer are exporting in H.265/HEVC, instead of H264

### ISSUE THREAD

**Issue by jonchui** [Awalz/SwiftyCam#184]
Is there any way to limit all video exports to use the Most compatible H264? (since Chrome browser still doesn't support H265/HEVC)

**Comment by jonandersen** [comment]
With this PR https://github.com/Awalz/SwiftyCam/pull/200 you should be able to specify the export format

**Comment by ShaikBaji1911** [comment]
Yeah @jonchui I was facing this issue but here we have 2 camera one is rear and the other is front camera so my case is 

In some device when we record the video the video is converting into the .h264 which is default but where as for iPhone X, it is taking as codeC type as HEVC and I have changed my code to

if #available(iOS 11.0, *)
{
let connection = movieFileOutput.connection(with: .video)
if movieFileOutput.availableVideoCodecTypes.contains(.h264)

        {
// Use the H.264 codec to encode the video.
 movieFileOutput.setOutputSettings([AVVideoCodecKey:AVVideoCodecType.h264], for: connection!)
        }
        }
this is really superb but the issue is when I give my default camera to = .front in viewDidLoad,then for front camera video recorded it is going as .h264 codeC and when I switch the camera to rear and record the video then at that time it is going as hevc but not as .h264

the same when in set my default camera to = .rear in viewDidLoad,then for rear camera video recorded it is going as .h264 codeC and when I switch the camera to front and record the video then at that time it is going as hevc but not as .h264 why this is behaving like this ??

what is this thing happening too
I was unable to know one more thing I have given default camera to rear or front but some times it is coming according to my requirement but not all times what is this issue




did you found any solution for this @jonchui  for both rear and front camera ??
