### ISSUE TITLE
Shuttering option

### ISSUE THREAD

**Issue by jackpaster** [Awalz/SwiftyCam#4]
@Awalz  I love your project very much, but I'm having a problem. Instead of taking one photo and presenting the next viewcontroller the image. I want the user to hold down on the camera button and burst of images will be taken until they let go of the camera button. Once they let go, the array of images taken will be passed onto the next view controller. Can you please implement this

**Comment by Awalz** [comment]
This is not a feature I would look into implementing in this project, but it can be achieved through this framework.

 Instead of using the SnapCamButton, you would need to implement your own custom button with a UILongPressGestureRecognizer, and call the function takePhoto() with a timer function when the long press began. You would also need to save the photos from the didTakePhoto delegate inside your view controller to your array. 

If you get stuck, I would be happy to look at your project.

Andrew

**Comment by jackpaster** [comment]
@Awalz I will try and code it tomorrow. But after tomorrow, if I need help wrapping the project up, could you please help me.
