### ISSUE TITLE
Adding SwiftyCamButton

### ISSUE THREAD

**Issue by kmb266** [Awalz/SwiftyCam#45]
I am new to SwiftyCam, but love the idea. I wanted to add the SwiftyCamButton as it says in the READ.ME and I followed what it said, but when I run the app on my phone, all I see is the AVcaptureSession open, and I cannot see the button. 
here is my code
`override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        //SwiftyCam
        let buttonFrame = CGRect(x: 200, y: 600, width: 200, height: 200)
        let captureButton = SwiftyCamButton(frame: buttonFrame)
    
        cameraDelegate = self
        captureButton.delegate = self
        
    }`
Any help would be appreciated thanks

**Comment by Awalz** [comment]
At no point to you add the captureButton to the view. To add a view programatically, you will need to call addSubview:

override func viewDidLoad() {

super.viewDidLoad()

let buttonFrame = CGRect(x: 200, y: 600, width: 200, height: 200)

 

let captureButton = SwiftyCamButton(frame: buttonFrame)

 

cameraDelegate = self 

captureButton.delegate = self

        view.addSubview(captureButton)

 }

Hope this helps

Andrew

On Wed, Apr 26, 2017 at 4:41 PM kmb266

<
mailto:kmb266 <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I am new to SwiftyCam, but love the idea. I wanted to add the SwiftyCamButton as it says in the READ.ME and I followed what it said, but when I run the app on my phone, all I see is the AVcaptureSession open, and I cannot see the button.

here is my code

`override func viewDidLoad() {

super.viewDidLoad()

// Do any additional setup after loading the view, typically from a nib.

//SwiftyCam let buttonFrame = CGRect(x: 200, y: 600, width: 200, height: 200) let captureButton = SwiftyCamButton(frame: buttonFrame) cameraDelegate = self captureButton.delegate = self }`

Any help would be appreciated thanks

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/Awalz/SwiftyCam/issues/45
, or

**Comment by kmb266** [comment]
Thanks! Finally got it to appear.

**Comment by alexcowley** [comment]
I have the code below, however button is not showing up in view.  Is there something I am missing?

```
import UIKit
import SwiftyCam

class CameraViewController: SwiftyCamViewController, SwiftyCamViewControllerDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()

        self.tabBarController?.tabBar.isHidden = true
        
        let buttonFrame = CGRect(x: 200, y:600, width:200, height:200)

        let captureButton = SwiftyCamButton(frame: buttonFrame)
        
        cameraDelegate = self
        
        captureButton.delegate = self
        
        view.addSubview(captureButton)
        
    }
```
@Awalz

**Comment by youngvz** [comment]
> I have the code below, however button is not showing up in view. Is there something I am missing?
> 
> ```
> import UIKit
> import SwiftyCam
> 
> class CameraViewController: SwiftyCamViewController, SwiftyCamViewControllerDelegate {
> 
>     override func viewDidLoad() {
>         super.viewDidLoad()
> 
>         self.tabBarController?.tabBar.isHidden = true
>         
>         let buttonFrame = CGRect(x: 200, y:600, width:200, height:200)
> 
>         let captureButton = SwiftyCamButton(frame: buttonFrame)
>         
>         cameraDelegate = self
>         
>         captureButton.delegate = self
>         
>         view.addSubview(captureButton)
>         
>     }
> ```
> @Awalz

@alexcowley Make sure you are setting the image of the captureButton, otherwise it will not display.
 > captureButton.setImage(UIImage(named: "focus"), for: .normal)
