### ISSUE TITLE
Only capture audio while recording video

### ISSUE THREAD

**Issue by kharmabum** [Awalz/SwiftyCam#47]
The default behavior of the SnapChat camera is to only add the audio capture device and change the audio session category once video capture begins. This is a great UX and would love to see it added to SwiftyCam.

**Comment by Awalz** [comment]
Agreed, it is on my list of improvements

On Mon, May 01, 2017 at 7:10 PM Juan-Carlos Foust

<
mailto:Juan-Carlos Foust <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

The default behavior of the SnapChat camera is to only add the audio capture device and change the audio session category once video capture begins. This is a great UX and would love to see it added to SwiftyCam.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/Awalz/SwiftyCam/issues/47
, or

**Comment by Awalz** [comment]
I have added this as a new feature in the newest version. Set the `audioEnabled` property to false.

Let me know if this does not work for you

Andrew
