### ISSUE TITLE
Set previewLayer's frame.

### ISSUE THREAD

**Issue by KaushalElsewhere** [Awalz/SwiftyCam#65]
Hi, firstly thanks for this awesome library.
I am trying to set previewLayer's frame according to my design (not as self.view.bounds)
please help.

**Comment by Awalz** [comment]
How are you initializing the SwiftyCamViewController? Can you provide a code snippet

**Comment by NicoleHinckley** [comment]
I'm also curious about this. I've just got a CameraViewController that is a subclass of SwiftyCamViewController with an IBOutlet for a UIView that I would like to be the previewLayer instead of the entire view.I tried doing something like just 
`  let preview = PreviewView(frame: camera.frame, videoGravity: videoGravity)
        super.previewLayer = preview 
        super.viewDidLoad()`

in my cameraVC viewDidLoad, but that just leaves a white screen for the camera. Any tips?

**Comment by MehdiChennoufi** [comment]
Hi everyone, i'm also interested to add a customise preview Layer on my design but I don't know where to start. Can you give me any advice ? Thank you

**Comment by bui2jp** [comment]
Hi,
I am also trying to change "previewLayer" based on my CameraViewController (this is subclass of SwiftyCamViewController).

The "previewLayer" is initialized in viewDidLoad() of SwiftyCamViewController. so I think we need to change this portion.

my changes is below, 

class CameraViewController: SwiftyCamViewController, SwiftyCamViewControllerDelegate {
 :
@IBOutlet weak var myPreviewLayer: PreviewView!
 :
 override func viewDidLoad() { 
  self.previewLayer = myPreviewLayer
  super.viewDidLoad()
 :

open class SwiftyCamViewController: UIViewController {
 :
 //change "private" to "public" in order to access myVC
 //fileprivate var previewLayer                 : PreviewView!
 var previewLayer                 : PreviewView!
 :
 override open func viewDidLoad() {
  super.viewDidLoad()
  //"previewLayer" is set from myVC. the below is not needed 
  //view = PreviewView(frame: view.frame, videoGravity: videoGravity)
  //previewLayer = view as! PreviewView!

 private func updatePreviewLayer(layer: AVCaptureConnection, orientation: AVCaptureVideoOrientation) {
  //previewLayer.frame does not need to be changed
  //previewLayer.frame = self.view.bounds

i hope this will help you.
