### ISSUE TITLE
Changing access control from 'public' to 'open'

### ISSUE THREAD

**Issue by lynchspin** [Awalz/SwiftyCam#68]
Sorry to bombard you, but when I try to implement the long press gesture delegate methods (and other methods) in my SwiftyCamViewController I get this error: "Overriding non-open instance method outside of its defining module"...  They talk about the problem here: https://github.com/MengTo/Spring/issues/197

Could you change the access control from 'public' to 'open' to accommodate on some of these methods? If you aren't using a SwiftyCamButton it's almost impossible to do anything unless these can be overridden in the SwiftyCamViewController

**Comment by Awalz** [comment]
I don't really follow what you are asking. What methods are you trying to override?

On Sat, Jun 10, 2017 at 5:20 PM Joseph

<
mailto:Joseph <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Sorry to bombard you, but when I try to implement the long press gesture delegate methods (and other methods) in my SwiftyCamViewController I get this error: "Overriding non-open instance method outside of its defining module"... They talk about the problem here:
https://github.com/MengTo/Spring/issues/197

Could you change the access control from 'public' to 'open' to accommodate on some of these methods? If you aren't using a SwiftyCamButton it's almost impossible to do anything unless these can be overridden in the SwiftyCamViewController

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/Awalz/SwiftyCam/issues/68
, or

**Comment by lynchspin** [comment]
These three methods specifically:

	public func buttonDidBeginLongPress() {
		startVideoRecording()
	}
	public func buttonDidEndLongPress() {
		stopVideoRecording()
	}

	public func longPressDidReachMaximumDuration() {
		stopVideoRecording()
	}

**Comment by Awalz** [comment]
I don't understand why you are looking to modify these. These methods are to handle the long press gestures of a SwiftyCam button. If you are using a custom button, you do not need to modify these.

**Comment by lynchspin** [comment]
My fault. I was thinking those were delegate methods for a long press gesture recognizer. Sorry about that.
